-- =============================================================================
-- StrideUp — Development Seed Data
-- =============================================================================
-- Run AFTER migrations/setup and AFTER E2E users are created (see e2e/auth.setup.ts).
--
-- Fixed E2E accounts (created by Playwright global setup when SUPABASE_SERVICE_ROLE_KEY is set):
--   e2e-user1@strideup.test       — primary authenticated user
--   e2e-user2@strideup.test       — second user (invite/chat specs)
--   e2e-inactive@strideup.test    — deactivated (is_active = false)
--
-- Promote an admin:
--   UPDATE public.profiles SET role = 'admin' WHERE user_id = '<uuid>';
-- =============================================================================

-- Example challenge seed (uncomment and replace USER_ID after users exist):
-- INSERT INTO public.challenges (name, description, start_date, end_date, step_goal, created_by, status)
-- VALUES (
--   'September Step Challenge',
--   'Walk 50,000 steps this month!',
--   CURRENT_DATE - INTERVAL '7 days',
--   CURRENT_DATE + INTERVAL '23 days',
--   50000,
--   'USER_ID_1',
--   'active'
-- );
